---

strategy:
  matrix:
    Black:
      python.version: '3.7'
      TOXENV: black-check
    Build:
      python.version: '3.6'
      TOXENV: build

variables:
  TOXENV: py
  POOL_IMAGE: ubuntu-16.04
  PYTHON: 'python'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(python.version)

- bash: |
    $PYTHON -m pip install -U tox
  displayName: Ensure prereqs

- bash: |
    if [[ $TOXENV == "py" ]];
    then
      $PYTHON -m tox -e coverage,codecov
    else
      $PYTHON -m tox
    fi
  displayName: Run tox

...
